title: "Complex Environmental Data and Modeling (CoEnv)"
author: "Luigi Ippoliti"
description: "University G.d'Annunzio, CHIETI-PESCARA"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Sezioni del Progetto di Ricerca
research_units:
  - name: Unità di Ricerca 1
    description: Descrizione della Unità di Ricerca 1.
  - name: Unità di Ricerca 2
    description: Descrizione della Unità di Ricerca 2.
  - name: Unità di Ricerca 3
    description: Descrizione della Unità di Ricerca 3.

# Principal Investigators
principal_investigators:
  - name: Nome Investigatore 1
    photo: /path/to/photo1.jpg
  - name: Nome Investigatore 2
    photo: /path/to/photo2.jpg
  - name: Nome Investigatore 3
    photo: /path/to/photo3.jpg

# Pubblicazioni
publications:
  - title: "Titolo della Pubblicazione 1"
    link: http://linkalla pubblicazione1.com
  - title: "Titolo della Pubblicazione 2"
    link: http://linkalla pubblicazione2.com
  - title: "Titolo della Pubblicazione 3"
    link: http://linkalla pubblicazione3.com


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md""}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:luigi.ippoliti@unich.it"}
  - {title: Github, icon: github, url: "https://github.com/Ippoliti1"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
